---
title: "Analysis behaviour - colorimetric assay"
author: "Enrico Bertolini"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# libraries

```{r}
if(!require("tidyverse")) {
  install.packages("tidyverse")
  library(tidyverse)
}

if(!require("ggh4x")) {
  install.packages("ggh4x")
  library(ggh4x)
}

if(!require("ggpubr")) {
  install.packages("ggpubr")
  library(ggpubr)
}

for (i in list.files("../R/", full.names = TRUE, pattern = '.R')) {
  source(i)
}
```

# 72-well assay

## plots

```{r}
read_tsv(file = "../data/behaviour_colorimetric_assay.tsv", show_col_types = FALSE) %>%
  filter(
    assay_type == "72-well colorimetric",
    two_choice == "noni juice vs grape juice"
  ) %>%
  select_all() -> df

p1 <- df %>%
  plot_PI(
    x_var = species,
    order_x = order_species(),
    title = "72-well colorimetric assay" 
  ) +
  force_panelsizes(rows = unit(20, "mm"),
                          cols = unit(15, "mm")) 

# p1

p2 <- df %>%
  plot_perc_feeding(
    x_var = species,
    order_x = order_species(),
    title = "72-well colorimetric assay" 
  ) +
  force_panelsizes(rows = unit(20, "mm"),
                          cols = unit(15, "mm"))

# p2

p <- ggarrange(p1, p2, ncol = 2, nrow = 1, align = "h")

p

ggsave("../output/72_well_colorimetric_Dtrio.png", 
       plot = p, 
       width = 6, 
       height = 5, 
       units = "cm")

```

## stats

```{r}
kruskal.test(df$preference_index ~ df$species)

dunn.test::dunn.test(
  x = df$preference_index,
  g = df$species,
  kw = TRUE,
  method = "bonferroni"
)
```


# petri dish assay

## plots

```{r}
read_tsv(file = "../data/behaviour_colorimetric_assay.tsv", show_col_types = FALSE) %>%
  filter(
    assay_type == "petri dish colorimetric",
    two_choice == "noni juice vs grape juice",
    strain %in% c(
      "Canton-S",
      "Oregon-R",
      "04",
      "196",
      "07",
      "28"
      )
  ) %>%
  select_all() -> df

df %>%
  plot_PI(
    x_var = strain,
    order_x = order_strains(),
    title = "petri dish colorimetric assay"
  ) +
  force_panelsizes(rows = unit(20, "mm"),
                          cols = unit(20, "mm")) 
```

## stats

```{r}
kruskal.test(df$preference_index ~ df$strain)

dunn.test::dunn.test(
  x = df$preference_index,
  g = df$strain,
  kw = TRUE,
  method = "bonferroni"
)
```

```{r}
sessionInfo()
```